site_name: gitpy
nav:
  - Home: README.md
  - Concepts:
    - Object Model: concepts/object_model.md
  - Contributing: contributing.md
theme:
  name: 'material'
repo_url: https://github.com/josix/gitpy
remote_branch: gh-pages
remote_name: origin
